labels:
    beer_cols:
        - Name
        - Type
        - ABV
        - Pour
        - Cost

    food_cols:
        - Bar Limon Pepper
        - Halfway Cooks

    merch_cols:
        - Item
        - Cost
